-- ============================================================
-- SAARTHI: Safe, additive refresh of the `schemes` table ONLY.
--
-- This script does NOT touch users, applications, documents,
-- notifications, reminders, grievances, or any other table.
-- It does NOT drop or truncate anything.
--
-- How it works:
--   - Matches existing rows by the `code` column (which is UNIQUE
--     in schema.sql), NOT by id -- so it is safe to run even if
--     your current `schemes` table already has rows with ids 1-7
--     (or any other ids) from an earlier seed.
--   - If a scheme with that code already exists, its details
--     (including `category`) are refreshed to the correct value
--     -- this is what fixes old labels such as "Micro Business" /
--     "Women & Child" -> "Employment" / "Women".
--   - If a scheme with that code does not exist yet, it is
--     inserted as a new row (MySQL assigns the next available id
--     automatically, so there is no risk of id collisions with
--     whatever is already in your table).
--   - Existing `applications`, `documents`, etc. that reference a
--     scheme_id are untouched, because matching rows keep their
--     original id -- only their column values are refreshed.
--
-- Run this against your existing saarthi_db database:
--   mysql -u root -p saarthi_db < schemes_upsert.sql
-- ============================================================

USE saarthi_db;

INSERT INTO schemes
    (code, title, ministry, category, benefit_amount, benefit_type, eligibility_min_age, eligibility_max_age, eligibility_max_income, gender_target, target_category, target_occupation, description, benefits_summary, documents_required, deadline, status)
VALUES
('PM-KISAN', 'Pradhan Mantri Kisan Samman Nidhi', 'Ministry of Agriculture & Farmers Welfare', 'Agriculture', 6000.00, 'Direct Benefit Transfer (DBT)', 18, 80, 400000.00, 'All', 'All', 'Farmer', 'Financial assistance of the amount given below per year provided to all landholding farmer families across India in three equal installments.', 'Rs. 6,000/year credited directly into bank account in 3 installments of Rs. 2,000.', 'Aadhaar Card, Land Holding Certificate, Bank Passbook', '2026-12-31', 'active'),
('PMAY-U', 'Pradhan Mantri Awas Yojana (Urban)', 'Ministry of Housing and Urban Affairs', 'Housing', 250000.00, 'Interest Subsidy / Capital Grant', 21, 70, 300000.00, 'All', 'All', 'All', 'Affordable housing subsidy for Economically Weaker Section (EWS) and Low Income Group (LIG) families building or purchasing their first pucca home.', 'Financial assistance up to Rs. 2.5 Lakh for house construction/renovation.', 'Aadhaar Card, Income Certificate, Property Documents, Bank Passbook', '2026-11-30', 'active'),
('PM-ABPMJAY', 'Ayushman Bharat - PM Jan Arogya Yojana', 'Ministry of Health and Family Welfare', 'Healthcare', 500000.00, 'Cashless Health Insurance Cover', 0, 100, 250000.00, 'All', 'All', 'All', 'World largest government-funded healthcare scheme providing cashless coverage of up to Rs. 5 Lakh per family per year for secondary and tertiary care hospitalization.', 'Cashless hospital cover up to Rs. 5,00,000 at 28,000+ empaneled hospitals.', 'Aadhaar Card, Ration Card / SECC 2011 proof', '2027-03-31', 'active'),
('PM-MUDRA', 'Pradhan Mantri MUDRA Yojana (Tarun)', 'Ministry of Finance', 'Entrepreneurship', 1000000.00, 'Collateral-free Micro Loan', 18, 65, 1500000.00, 'All', 'All', 'Entrepreneur', 'Loans up to Rs. 10 Lakh to non-corporate, non-farm small/micro enterprises for setting up or expanding business operations.', 'Collateral-free business credit up to Rs. 10 Lakhs with subsidized interest rates.', 'Aadhaar Card, PAN Card, Business Plan Project Report, Bank Statement', '2026-10-15', 'active'),
('NSP-POSTMATRIC', 'National Post-Matric Scholarship Scheme', 'Ministry of Social Justice and Empowerment', 'Education', 45000.00, 'Academic Fee Subsidy + Maintenance', 15, 30, 250000.00, 'All', 'SC, ST, OBC', 'Student', 'Financial aid to meritorious students belonging to minority/reserved categories pursuing higher education post 10th grade.', 'Full tuition fee reimbursement + monthly stipend up to Rs. 45,000/year.', 'Aadhaar Card, Caste Certificate, Income Certificate, Previous Marksheets', '2026-09-30', 'active'),
('SSY-GIRL', 'Sukanya Samriddhi Yojana', 'Ministry of Women and Child Development', 'Women', 150000.00, 'High Interest Savings Benefit', 0, 10, 1000000.00, 'Female', 'All', 'All', 'Small deposit scheme for the girl child offering highest tax-free government interest rates (8.2%) to secure her future education and marriage.', 'Tax benefit under 80C + 8.2% annual interest compounded yearly.', 'Birth Certificate of Girl Child, Parents Aadhaar Card, Address Proof', '2027-12-31', 'active'),
('PM-SVANIDHI', 'PM Street Vendor AtmaNirbhar Nidhi', 'Ministry of Housing and Urban Affairs', 'Employment', 50000.00, 'Micro Credit Loan + Cashback', 18, 65, 300000.00, 'All', 'All', 'Street Vendor', 'Special micro-credit facility providing affordable collateral-free working capital loans up to Rs. 50,000 to street vendors affected by economic disruption.', 'Enhanced credit limit on timely repayment + 7% interest subsidy.', 'Aadhaar Card, Vending Certificate / ID Card, Bank Account', '2026-12-15', 'active'),
('PMFBY', 'Pradhan Mantri Fasal Bima Yojana', 'Ministry of Agriculture & Farmers Welfare', 'Agriculture', 200000.00, 'Crop Insurance Cover', 18, 70, 500000.00, 'All', 'All', 'Farmer', 'Low-premium crop insurance scheme protecting farmers against yield losses caused by natural calamities, pests and diseases across Kharif and Rabi seasons.', 'Comprehensive risk cover with farmer premium as low as 1.5% to 5% of the sum insured, balance subsidized by government.', 'Aadhaar Card, Land Records, Bank Passbook, Sowing Certificate', '2026-11-15', 'active'),
('PM-KSY', 'Pradhan Mantri Krishi Sinchayee Yojana', 'Ministry of Jal Shakti', 'Agriculture', 100000.00, 'Irrigation Infrastructure Subsidy', 18, 75, 400000.00, 'All', 'All', 'Farmer', 'Har Khet Ko Pani initiative ensuring assured irrigation and promoting water-use efficiency through micro-irrigation for every farm in the country.', 'Subsidy up to Rs. 1 Lakh per hectare for drip and sprinkler irrigation equipment.', 'Aadhaar Card, Land Holding Certificate, Water Source Proof', '2026-12-20', 'active'),
('PMAY-G', 'Pradhan Mantri Awas Yojana (Gramin)', 'Ministry of Rural Development', 'Housing', 130000.00, 'Housing Construction Assistance', 18, 100, 300000.00, 'All', 'All', 'All', 'Provides pucca houses with basic amenities to houseless and inadequately housed rural families identified through the SECC 2011 database.', 'Rs. 1.2 to 1.3 Lakh direct construction assistance plus 90/95 days of MGNREGA wage support for construction.', 'Aadhaar Card, SECC 2011 Proof, Bank Passbook, Land Ownership/Allotment Document', '2026-10-31', 'active'),
('PMAY-ARHC', 'Affordable Rental Housing Complexes', 'Ministry of Housing and Urban Affairs', 'Housing', 50000.00, 'Affordable Rental Housing Access', 18, 60, 300000.00, 'All', 'All', 'Migrant Worker', 'Converts government-funded vacant housing stock into affordable rental complexes to provide dignified living to urban migrant workers and the urban poor close to their workplace.', 'Subsidized rental housing units with basic amenities at concessional monthly rent.', 'Aadhaar Card, Employer/Employment Proof, Migration Certificate', '2026-09-30', 'active'),
('JSY', 'Janani Suraksha Yojana', 'Ministry of Health and Family Welfare', 'Healthcare', 1400.00, 'Maternity Cash Assistance', 19, 45, 250000.00, 'Female', 'All', 'All', 'Safe motherhood intervention promoting institutional delivery among pregnant women, particularly in low-performing states, to reduce maternal and infant mortality.', 'Cash assistance for institutional delivery plus free transport and postnatal care support.', 'Aadhaar Card, Pregnancy Registration Card, BPL Certificate (if applicable), Bank Passbook', '2027-01-31', 'active'),
('PMSBY', 'Pradhan Mantri Suraksha Bima Yojana', 'Ministry of Finance', 'Healthcare', 200000.00, 'Accidental Insurance Cover', 18, 70, 1000000.00, 'All', 'All', 'All', 'Affordable government-backed accident insurance scheme offering coverage for accidental death and disability at a nominal annual premium.', 'Rs. 2 Lakh cover on accidental death or full disability, Rs. 1 Lakh for partial disability, at a premium of only Rs. 20/year.', 'Aadhaar Card, Bank Account linked to Aadhaar', '2026-05-31', 'active'),
('PM-YASASVI', 'PM Young Achievers Scholarship Award Scheme for Vibrant India', 'Ministry of Social Justice and Empowerment', 'Education', 125000.00, 'Merit Scholarship', 13, 20, 250000.00, 'All', 'OBC, EBC, DNT', 'Student', 'Financial support to meritorious students from OBC, EBC and DNT communities studying in classes 9 to 12 and top-ranked institutions.', 'Scholarship amount up to Rs. 1,25,000 per year depending on class and institution.', 'Aadhaar Card, Caste Certificate, Income Certificate, Previous Year Marksheet', '2026-08-31', 'active'),
('NMMSS', 'National Means-cum-Merit Scholarship Scheme', 'Ministry of Education', 'Education', 12000.00, 'Merit-cum-Means Scholarship', 13, 16, 350000.00, 'All', 'All', 'Student', 'Scholarship for economically weaker meritorious students to reduce the dropout rate at the transition from class 8 to class 9.', 'Rs. 12,000 per year (Rs. 1,000/month) for classes 9 through 12.', 'Aadhaar Card, Income Certificate, Class 8 Marksheet, Bank Passbook', '2026-11-30', 'active'),
('PMMVY', 'Pradhan Mantri Matru Vandana Yojana', 'Ministry of Women and Child Development', 'Women', 5000.00, 'Maternity Benefit Cash Transfer', 19, 45, 800000.00, 'Female', 'All', 'All', 'Cash incentive for pregnant and lactating mothers for their first living child to partially compensate for wage loss and encourage better health and nutrition practices.', 'Rs. 5,000 paid in three installments directly to the bank account, in addition to Rs. 1,000 under JSY for institutional delivery.', 'Aadhaar Card, MCP Card, Bank Passbook, Husband Aadhaar Card', '2026-12-31', 'active'),
('MGNREGA', 'Mahatma Gandhi National Rural Employment Guarantee Act', 'Ministry of Rural Development', 'Employment', 24000.00, 'Guaranteed Wage Employment', 18, 60, 300000.00, 'All', 'All', 'Rural Laborer', 'Legal guarantee of 100 days of wage employment in a financial year to every rural household whose adult members volunteer to do unskilled manual work.', 'Guaranteed 100 days of wage employment per household per year at notified wage rates.', 'Aadhaar Card, Job Card, Bank Passbook', '2027-03-31', 'active'),
('APY', 'Atal Pension Yojana', 'Ministry of Finance', 'Pension', 60000.00, 'Guaranteed Monthly Pension', 18, 40, 1000000.00, 'All', 'All', 'All', 'Guaranteed minimum pension scheme for workers in the unorganized sector, providing a fixed monthly pension after age 60 based on the contribution slab chosen.', 'Guaranteed monthly pension of Rs. 1,000 to Rs. 5,000 after age 60, depending on contribution amount and age of joining.', 'Aadhaar Card, Bank Passbook, Mobile Number linked to Aadhaar', '2026-12-31', 'active'),
('PM-SYM', 'Pradhan Mantri Shram Yogi Maan-dhan', 'Ministry of Labour and Employment', 'Pension', 36000.00, 'Old Age Pension', 18, 40, 180000.00, 'All', 'All', 'Unorganized Sector Worker', 'Voluntary and contributory pension scheme for unorganized sector workers such as street vendors, rickshaw pullers and domestic workers, ensuring a monthly pension after age 60.', 'Minimum assured monthly pension of Rs. 3,000 after age 60 with matching government contribution.', 'Aadhaar Card, Bank Passbook, Income Self-Declaration', '2026-10-31', 'active'),
('STANDUP-INDIA', 'Stand-Up India Scheme', 'Ministry of Finance', 'Entrepreneurship', 10000000.00, 'Bank Loan for Greenfield Enterprise', 18, 65, 2000000.00, 'All', 'SC, ST, Women', 'Entrepreneur', 'Facilitates bank loans between Rs. 10 Lakh and Rs. 1 Crore to at least one SC/ST borrower and one woman borrower per bank branch for setting up a greenfield enterprise.', 'Composite loan covering up to 75% of project cost for manufacturing, trading or services sector ventures.', 'Aadhaar Card, PAN Card, Business Project Report, Caste Certificate (if applicable), Bank Statement', '2026-11-15', 'active'),
('MSSC', 'Mahila Samman Savings Certificate', 'Ministry of Finance', 'Women', 200000.00, 'Small Savings Interest Scheme', 10, 100, 5000000.00, 'Female', 'All', 'All', 'Two-year small savings scheme exclusively for women and girls offering an assured government interest rate on deposits up to Rs. 2 Lakh, with partial withdrawal facility after one year.', 'Assured 7.5% annual interest on deposits up to Rs. 2 Lakh with a 2-year maturity and partial withdrawal option.', 'Aadhaar Card, Bank/Post Office KYC Form, Passport Size Photograph', '2026-12-31', 'active'),
('PM-VISHWAKARMA', 'PM Vishwakarma Yojana', 'Ministry of Micro, Small and Medium Enterprises', 'Employment', 300000.00, 'Skill Training + Collateral-free Credit Support', 18, 65, 500000.00, 'All', 'All', 'Artisan / Craftsperson', 'Support scheme for traditional artisans and craftspeople such as carpenters, tailors, potters and blacksmiths, offering skill upgradation training, modern toolkits and collateral-free credit to strengthen their trade.', 'Rs. 15,000 toolkit incentive, daily skill-training stipend, and collateral-free loans up to Rs. 3 Lakh in two tranches at concessional interest.', 'Aadhaar Card, Trade/Community Verification Certificate, Bank Passbook', '2026-11-30', 'active'),
('IGNOAPS', 'Indira Gandhi National Old Age Pension Scheme', 'Ministry of Rural Development', 'Pension', 12000.00, 'Monthly Social Assistance Pension', 60, 120, 100000.00, 'All', 'All', 'All', 'Monthly pension assistance under the National Social Assistance Programme for elderly citizens belonging to Below Poverty Line households, providing basic financial security in old age.', 'Monthly pension of Rs. 200 to Rs. 500 from the Centre, further topped up by most State Governments, credited directly to the bank account.', 'Aadhaar Card, BPL Ration Card, Age Proof, Bank Passbook', '2027-03-31', 'active'),
('SISFS', 'Startup India Seed Fund Scheme', 'Ministry of Commerce and Industry (DPIIT)', 'Entrepreneurship', 2000000.00, 'Seed Grant + Convertible Debenture Funding', 18, 60, 10000000.00, 'All', 'All', 'Startup Founder', 'Provides early-stage financial assistance to DPIIT-recognized startups for proof of concept, prototype development, product trials and market entry through eligible incubators.', 'Grant up to Rs. 20 Lakh for validation and prototyping, plus up to Rs. 50 Lakh convertible debenture support for market launch.', 'Aadhaar Card, PAN Card, DPIIT Startup Recognition Certificate, Business Plan/Pitch Deck', '2026-10-31', 'active')
ON DUPLICATE KEY UPDATE
    title = VALUES(title),
    ministry = VALUES(ministry),
    category = VALUES(category),
    benefit_amount = VALUES(benefit_amount),
    benefit_type = VALUES(benefit_type),
    eligibility_min_age = VALUES(eligibility_min_age),
    eligibility_max_age = VALUES(eligibility_max_age),
    eligibility_max_income = VALUES(eligibility_max_income),
    gender_target = VALUES(gender_target),
    target_category = VALUES(target_category),
    target_occupation = VALUES(target_occupation),
    description = VALUES(description),
    benefits_summary = VALUES(benefits_summary),
    documents_required = VALUES(documents_required),
    deadline = VALUES(deadline),
    status = VALUES(status);